import {useEffect,useState} from 'react';
import {useNavigate,useParams,Link} from 'react-router-dom';
import {ArrowLeft,Save,LoaderCircle,MapPin,Clock} from 'lucide-react';
import Navbar from '../components/Navbar';
import api from '../services/api';

export default function EditJourney(){
 const {id}=useParams(),nav=useNavigate();
 const [form,setForm]=useState({origin:'',destination:'',startTime:'',destinationAlertRadiusMeters:1000});
 const [busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{api.get(`/trip/${id}`).then(r=>{const t=r.data;setForm({origin:t.origin,destination:t.destination,startTime:new Date(t.startTime).toISOString().slice(0,16),destinationAlertRadiusMeters:t.destinationAlertRadiusMeters||1000});}).catch(e=>setError(e.response?.data?.msg||'Unable to load journey.')).finally(()=>setBusy(false))},[id]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(e){e.preventDefault();const alertRadius=Number(form.destinationAlertRadiusMeters);if(!Number.isFinite(alertRadius)||alertRadius<100||alertRadius>50000){setError('Choose an alert distance between 100 m and 50 km.');return;}setError('');setSaving(true);try{await api.put(`/trip/${id}`,{...form,startTime:new Date(form.startTime).toISOString(),destinationAlertRadiusMeters:alertRadius});nav(`/monitor/${id}`)}catch(e){setError(e.response?.data?.msg||e.response?.data?.error||'Unable to update journey.')}finally{setSaving(false)}}
 return <><Navbar app/><main className="journey-shell"><div className="journey-intro"><Link to="/dashboard" className="back-link"><ArrowLeft size={15}/> Dashboard</Link><span className="eyebrow">EDIT JOURNEY</span><h1>Update your travel plan.</h1><p>Changing the route rebuilds the expected road route used by Travaio's safety engine.</p></div><section className="form-card edit-journey-card">{busy?<LoaderCircle className="spin"/>:<form onSubmit={save}>{error&&<div className="form-error">{error}</div>}<div className="field"><label>Starting point</label><div className="input-with-icon"><MapPin size={17}/><input required value={form.origin} onChange={e=>set('origin',e.target.value)}/></div></div><div className="field"><label>Destination</label><div className="input-with-icon"><MapPin size={17}/><input required value={form.destination} onChange={e=>set('destination',e.target.value)}/></div></div><div className="field"><label>Planned start</label><div className="input-with-icon"><Clock size={17}/><input required type="datetime-local" value={form.startTime} onChange={e=>set('startTime',e.target.value)}/></div></div><div className="field destination-alert-setting"><label>Destination alert</label><div className="input-with-icon"><Clock size={17}/><input type="number" min="100" max="50000" step="50" value={form.destinationAlertRadiusMeters} onChange={e=>set('destinationAlertRadiusMeters',e.target.value)} placeholder="1000" /></div><small>Default is 1 km. Enter any distance from 100 m to 50 km. Quick values: 500 m, 1 km, 2 km.</small></div><div className="editor-actions"><button className="primary-btn" disabled={saving}>{saving?<><LoaderCircle className="spin" size={16}/> Rebuilding route…</>:<><Save size={16}/> Save journey</>}</button><Link className="secondary-btn" to={`/monitor/${id}`}>Cancel</Link></div></form>}</section></main></>
}
