import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {useNavigate,useParams,Link} from 'react-router-dom';
import {ArrowLeft,ShieldCheck,AlertTriangle,LocateFixed,CheckCircle2,Phone,Navigation,Clock3,MapPin,Flag,RefreshCw} from 'lucide-react';
import {MapContainer,TileLayer,Polyline,Marker,Circle,Popup,useMap} from 'react-leaflet';
import L from 'leaflet';
import Navbar from '../components/Navbar';
import api from '../services/api';
import 'leaflet/dist/leaflet.css';

const icon=new L.DivIcon({className:'user-marker',html:'<div></div>',iconSize:[18,18],iconAnchor:[9,9]});
const R=6371000;
const distance=(a,b)=>{const p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180;const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};
function MapUpdater({center}){const map=useMap();useEffect(()=>{if(center)map.setView([center.lat,center.lng],Math.max(13,map.getZoom()));},[center,map]);return null;}

export default function Monitor(){
 const {id}=useParams(),nav=useNavigate();const [trip,setTrip]=useState(null),[error,setError]=useState(''),[position,setPosition]=useState(null),[watching,setWatching]=useState(false),[busy,setBusy]=useState(false),[arrival,setArrival]=useState(false),[now,setNow]=useState(Date.now());
 const watchRef=useRef(null),pollRef=useRef(null);
 const route=useMemo(()=>trip?.routeCoordinates||[],[trip]);
 const load=useCallback(async()=>{try{const r=await api.get(`/trip/${id}`);setTrip(r.data);if(r.data.lastLocation)setPosition(r.data.lastLocation);}catch(e){setError(e.response?.data?.msg||'Unable to load journey.');}},[id]);
 useEffect(()=>{load();return()=>{if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current);if(pollRef.current)clearInterval(pollRef.current);}},[load]);
 useEffect(()=>{if(trip?.status==='active'){pollRef.current=setInterval(load,10000);return()=>clearInterval(pollRef.current);}},[trip?.status,load]);
 const notify=msg=>{if('Notification'in window&&Notification.permission==='granted')new Notification('Travaio',{body:msg});};
 async function start(){setError('');if(!navigator.geolocation){setError('This browser does not support location services.');return;}setBusy(true);try{const r=await api.post(`/trip/${id}/start`);setTrip(r.data);if(Notification.permission==='default')await Notification.requestPermission();const currentRoute=r.data.routeCoordinates||[];if(!currentRoute.length)throw new Error('The road route could not be prepared. Please open the journey again.');watchRef.current=navigator.geolocation.watchPosition(async pos=>{const p={lat:pos.coords.latitude,lng:pos.coords.longitude};setPosition(p);try{const lr=await api.post(`/trip/${id}/location`,{location:p,accuracy:pos.coords.accuracy});if(lr.data.incidentStarted)notify('A significant route deviation was detected. Please confirm that you are safe.');if(lr.data.arrivalAlert){setArrival(true);notify(`You are within ${(Number(lr.data.arrivalRadiusMeters||trip?.destinationAlertRadiusMeters||1000)/1000).toFixed(1)} km of your destination.`);}setTrip(t=>t?{...t,lastLocation:p,lastLocationAt:new Date().toISOString(),deviationDistanceMeters:lr.data.deviationDistanceMeters,safety:lr.data.safety}:t);}catch{}},err=>setError(err.code===1?'Location permission was denied. Please allow location access.':err.message||'Unable to read your location.'),{enableHighAccuracy:true,maximumAge:3000,timeout:20000});setWatching(true);}catch(e){setError(e.response?.data?.msg||e.response?.data?.error||e.message||'Unable to start monitoring.')}finally{setBusy(false)}}
 async function safe(){try{const r=await api.post(`/trip/${id}/safety/acknowledge`);setTrip(r.data.trip);}catch(e){setError(e.response?.data?.msg||'Could not confirm your safety.')}}
 async function finish(){setBusy(true);try{const r=await api.put(`/trip/${id}`,{status:'completed'});setTrip(r.data);if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current);setWatching(false);nav('/dashboard');}catch(e){setError(e.response?.data?.msg||'Unable to complete journey.')}finally{setBusy(false)}}
 const center=position||trip?.originCoords;const line=route.map(p=>[p.lat,p.lng]);const remaining=position&&trip?.destinationCoords?distance(position,trip.destinationCoords):null;const state=trip?.safety?.state||'normal';const deviation=Number(trip?.deviationDistanceMeters||0);const reminder=trip?.safety?.reminderCount||0;
 if(!trip&&!error)return <><Navbar app/><main className="loading-screen"><RefreshCw className="spin"/> Loading journey…</main></>;
 if(!trip)return <><Navbar app/><main className="container section-pad"><div className="form-error">{error}</div></main></>;
 return <><Navbar app/><main className="monitor-shell"><div className="monitor-top"><Link to="/dashboard" className="back-link"><ArrowLeft size={15}/> Dashboard</Link><div><span className="eyebrow">{trip.status==='active'?'LIVE JOURNEY':'JOURNEY'}</span><h1>{trip.origin} <span>→</span> {trip.destination}</h1></div><div className={`monitor-state ${state}`}><i></i>{state==='checking'?'Safety check required':state==='escalated'?'Escalated':trip.status==='completed'?'Completed':watching?'Monitoring live':'Ready'}</div></div>{error&&<div className="form-error monitor-error">{error}</div>}{arrival&&<div className="arrival-banner"><CheckCircle2 size={19}/><div><strong>You're close to your destination.</strong><span>Travaio detected that you are within {(Number(trip.destinationAlertRadiusMeters||1000)/1000).toFixed(1)} km of {trip.destination}.</span></div></div>}<div className="monitor-layout"><section className="live-map"><div className="map-toolbar"><span><Navigation size={15}/> Planned road route</span><span>{watching?'● GPS updating':'○ GPS waiting'}</span></div>{center&&<MapContainer center={[center.lat,center.lng]} zoom={13} scrollWheelZoom><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><MapUpdater center={center}/>{line.length>1&&<Polyline positions={line} pathOptions={{color:'#087f78',weight:6,opacity:.9}}/>}{position&&<><Marker position={[position.lat,position.lng]} icon={icon}><Popup>Your current location</Popup></Marker><Circle center={[position.lat,position.lng]} radius={Math.max(15,Number(trip.lastLocationAccuracy||25))} pathOptions={{color:'#087f78',fillOpacity:.08}}/></>}{trip.destinationCoords&&<Marker position={[trip.destinationCoords.lat,trip.destinationCoords.lng]}><Popup>{trip.destination}</Popup></Marker>}</MapContainer>}</section><aside className="monitor-panel"><div className="monitor-card hero-status"><div className="status-row"><div><span className="eyebrow">SAFETY STATUS</span><h2>{state==='normal'?(watching?'Journey looks normal':'Ready when you are'):state==='checking'?'Please confirm you are safe':'Emergency contact flow triggered'}</h2></div><ShieldCheck size={25}/></div><p>{state==='normal'
 ? 'Travaio is comparing your live location with the planned road route.'
 : state==='checking'
 ? 'Your route changed significantly. If you do not respond to the safety checks, your emergency contacts will be notified.'
 : trip.safety?.escalationNotifiedAt
 ? 'Travaio has notified your emergency contact by email. Please contact them directly as well.'
 : 'The three safety checks were not acknowledged. Emergency escalation has been recorded, but email delivery is not configured yet.'}</p>{state==='checking'&&<div className="safety-actions"><div className="reminder-count">Check {reminder} <span>/ 3</span></div><button className="safe-button-large" onClick={safe}><CheckCircle2 size={17}/> I'm safe</button></div>}{state==='escalated'&&<Link className="secondary-btn wide" to="/emergency-contacts"><Phone size={15}/> View emergency contacts</Link>}{state==='normal'&&trip.status!=='completed'&&!watching&&<button className="primary-btn wide" onClick={start} disabled={busy}><LocateFixed size={17}/>{busy?'Preparing monitoring…':'Start live monitoring'}</button>}</div><div className="monitor-card metrics-card"><div><span>PLANNED</span><strong>{(Number(trip.routeDistanceMeters||0)/1000).toFixed(1)} km</strong></div><div><span>REMAINING</span><strong>{remaining!=null?`${(remaining/1000).toFixed(1)} km`:'—'}</strong></div><div><span>ROUTE OFFSET</span><strong className={deviation>250?'warn':''}>{deviation?`${Math.round(deviation)} m`:'0 m'}</strong></div><div><span>DESTINATION ALERT</span><strong>{(Number(trip.destinationAlertRadiusMeters||1000)/1000).toFixed(1)} km</strong></div></div><div className="monitor-card timeline"><div className="timeline-item"><span className="timeline-dot done"></span><div><strong>Journey planned</strong><small>{new Date(trip.createdAt).toLocaleString()}</small></div></div><div className="timeline-item"><span className={`timeline-dot ${watching?'done':''}`}></span><div><strong>{watching?'Live monitoring active':'Monitoring not started'}</strong><small>{trip.monitoringStartedAt?new Date(trip.monitoringStartedAt).toLocaleString():'Start when you are ready'}</small></div></div><div className="timeline-item"><span className={`timeline-dot ${state==='checking'||state==='escalated'?'alert':''}`}></span><div><strong>{state==='normal'?'No safety incident':'Safety system engaged'}</strong><small>{state==='normal'?'No unusual route change is currently active.':state==='checking'?'Waiting for your response.':'Emergency escalation recorded.'}</small></div></div></div>{watching&&<button className="secondary-btn wide" onClick={finish} disabled={busy}><Flag size={15}/> {busy?'Completing…':'Mark journey completed'}</button>}</aside></div></main></>;
}
